// Independent semantic fixtures from #2159's reviewed plan, not engine exports.
// `expected` specifies the selected deterministic fixture, not every legal WAR run.
export const scenarios = [
  { id: 'P01', stimulus: 'One task; two independent approving lenses on the candidate', script: ['worker commits candidate', 'correctness approves', 'security approves', 'gate exits zero'], evidence: ['audit-result', 'gate', 'git-state'], minimum: 'adapter-contract', expected: { approvals: 2, blockingFindings: [], integrationCount: 1, gateExit: 0 } },
  { id: 'P02', stimulus: 'Major defect then corrected revision', script: ['first audit requests changes with Major', 'fix commits new candidate', 'both seats approve new candidate'], evidence: ['audit-result', 'git-state'], minimum: 'adapter-contract', expected: { blockedIntegrationCount: 0, freshApprovals: 2, integrationCount: 1, fixAttempts: 1 } },
  { id: 'P03', stimulus: 'Approval names a stale revision', script: ['auditor approves old SHA'], evidence: ['audit-result'], minimum: 'adapter-contract', expected: { approvalAccepted: false, integrationCount: 0 } },
  { id: 'P04', stimulus: 'Malformed/null/wrong-role/duplicate/truncated role response', script: ['transport returns invalid response', 'fixture chooses immediate explicit failure, no retry'], evidence: ['transport'], minimum: 'adapter-contract', expected: { result: 'invalid-result', retryCount: 0, integrationCount: 0 } },
  { id: 'P05', stimulus: 'Independent tasks a/b, then c depends on a', script: ['a/b start from frozen base', 'a integrates', 'c observes integrated a'], evidence: ['dispatch', 'git-state'], minimum: 'adapter-contract', expected: { frozenBasePreserved: true, dependencyObserved: true, tasksCompleted: ['a', 'b', 'c'] } },
  { id: 'P06', stimulus: 'Overlapping workers/auditors; one call throws; capacity two', script: ['start two roles', 'one rejects', 'queued role acquires released permit', 'drain completes'], evidence: ['dispatch'], minimum: 'adapter-contract', expected: { peakDispatches: 2, leakedPermits: 0, pendingDispatches: 0, drain: 'completed' } },
  { id: 'P07', stimulus: 'Gate exits one on the candidate', script: ['gate fails with captured artifact'], evidence: ['gate'], minimum: 'adapter-contract', expected: { gateExit: 1, integrationCount: 0, result: 'gate-failed' } },
  { id: 'P08', stimulus: 'Floor requirement failure contrasted with Git error', script: ['floor probe returns one', 'separate probe returns two'], evidence: ['floor'], minimum: 'adapter-contract', expected: { requirementResult: 'requirement-failed', gitErrorResult: 'git-error', integrationCount: 0 } },
  { id: 'P09', stimulus: 'An enabled test/package/acceptance floor is missing', script: ['required floor evidence absent', 'no sanctioned exemption'], evidence: ['floor'], minimum: 'adapter-contract', expected: { result: 'missing-floor', integrationCount: 0, exemption: null } },
  { id: 'P10', stimulus: 'Rebase changes relevant code after approval', script: ['approve old tip', 'rebase changes relevant code', 'fresh audit required'], evidence: ['audit-result', 'git-state'], minimum: 'adapter-contract', expected: { oldApprovalTransferred: false, freshAuditRequired: true, integrationCount: 0 } },
  { id: 'P11', stimulus: 'Foreign writer advances the destination before landing', script: ['remote advances', 'non-force landing rejects stale destination'], evidence: ['git-state'], minimum: 'fixture-integration', expected: { result: 'land-stale', forcePushes: 0, foreignCommitRetained: true } },
  { id: 'P12', stimulus: 'Kill after worker commit, then restart', script: ['worker commit persists', 'controller killed', 'new process reconciles existing commit'], evidence: ['process', 'git-state'], minimum: 'fixture-integration', expected: { workerCommitRetained: true, destructiveResets: 0, duplicateWork: 0 } },
  { id: 'P13', stimulus: 'Kill after remote push before ledger write', script: ['push candidate', 'kill at after-push checkpoint', 'new process reads remote and stale ledger'], evidence: ['process', 'git-state', 'ledger'], minimum: 'fixture-integration', expected: { reconciledFrom: 'git', duplicateLandings: 0, ledgerRepaired: true, remoteCommitRetained: true } },
  { id: 'P14', stimulus: 'Ledger ahead, Git ahead, and unexplained commit probes', script: ['repair ledger toward known Git state', 'halt for unexplained Git state'], evidence: ['git-state', 'ledger'], minimum: 'fixture-integration', expected: { ledgerAhead: 'repair-records', gitAhead: 'repair-records', unexplained: 'halt', destructiveResets: 0 } },
  { id: 'P15', stimulus: 'Issue persisted but response lost', script: ['create with correlation ID', 'service drops response', 'restart searches correlation ID'], evidence: ['service-log'], minimum: 'fixture-integration', expected: { createdIssues: 1, correlationRecovered: true, duplicateIssues: 0 } },
  { id: 'P16', stimulus: 'Every disposition and carried findings survive restart', script: ['persist absorb/follow-up/note/ask', 'restart with no operator ruling'], evidence: ['ledger'], minimum: 'adapter-contract', expected: { dispositions: ['absorb', 'follow-up', 'note', 'ask'], lostFindings: [], operatorDecisionRequired: true } },
  { id: 'P17', stimulus: 'Provision command fails before work', script: ['provision exits nonzero'], evidence: ['provision', 'dispatch'], minimum: 'adapter-contract', expected: { workerDispatches: 0, result: 'env-blocked', provisionExit: 1 } },
  { id: 'P18', stimulus: 'Auditor attempts a write through a supported tool', script: ['observed write attempt reaches host enforcement', 'host denies'], evidence: ['denial', 'git-state'], minimum: 'actual-runtime', expected: { attempted: true, denied: true, changedPaths: [], createdRefs: [] } },
  { id: 'P19', stimulus: 'Own-file write and sibling/main/traversal/symlink escapes', script: ['own write succeeds', 'each out-of-scope write reaches policy and is denied'], evidence: ['denial', 'git-state'], minimum: 'actual-runtime', expected: { ownWrite: 'allowed', siblingWrite: 'denied', mainWrite: 'denied', traversalWrite: 'denied', symlinkWrite: 'denied' } },
  { id: 'P20', stimulus: 'Multi-file add/update/delete/rename patch includes forbidden destination', script: ['host receives patch with all path forms', 'forbidden destination causes denial'], evidence: ['denial'], minimum: 'actual-runtime', expected: { checkedForms: ['add', 'update', 'delete', 'rename-source', 'rename-destination'], forbiddenDestination: 'denied', mutationCount: 0 } },
  { id: 'P21', stimulus: 'Invalid provenance, protected existing lesson, valid scoped lesson', script: ['invalid/protected writes denied', 'valid scoped write allowed', 'publication redaction applies'], evidence: ['denial', 'memory'], minimum: 'actual-runtime', expected: { invalidProvenance: 'denied', protectedLesson: 'denied', validLesson: 'allowed', redactionApplied: true } },
  { id: 'P22', stimulus: 'Cancel while child or permission request is pending', script: ['cancel controller', 'terminate owned children', 'retain incomplete state'], evidence: ['process', 'dispatch'], minimum: 'fixture-integration', expected: { dispatchesAfterCancel: 0, liveDescendants: 0, result: 'incomplete' } },
  { id: 'P23', stimulus: 'Submodule content task then superproject gitlink bump', script: ['submodule artifact commits first', 'superproject references exact artifact'], evidence: ['git-state'], minimum: 'fixture-integration', expected: { ownershipPreserved: true, submoduleBeforeSuperproject: true, matchingArtifact: true } },
  { id: 'P24', stimulus: 'Cleanup with/without ownership and landing proofs', script: ['owned clean landed work removed', 'foreign/dirty/unexplained work retained'], evidence: ['git-state', 'cleanup'], minimum: 'fixture-integration', expected: { ownedLanded: 'removed', foreign: 'retained', dirty: 'retained', unexplained: 'retained' } },
  { id: 'P25', stimulus: 'Wrong hook selection or missing packaged asset despite zero client exit', script: ['client exits zero', 'package inspection rejects missing/wrong component'], evidence: ['package'], minimum: 'actual-runtime', expected: { clientExit: 0, compatible: false, result: 'package-invalid' } },
  { id: 'P26', stimulus: 'Unsupported model/effort or unavailable credentials/rate limit', script: ['profile or infrastructure refuses launch', 'no silent downgrade'], evidence: ['transport'], minimum: 'adapter-contract', expected: { profileChanged: false, result: 'unavailable', successfulAudits: 0 } },
].map(row => Object.freeze({ ...row, runtimes: ['claude', 'codex'], fixtureVersion: 1, binding: 'pending-T5-T7' }))

function freeze(value) {
  if (value && typeof value === 'object') {
    for (const child of Object.values(value)) freeze(child)
    Object.freeze(value)
  }
}
freeze(scenarios)
