; The alex profile: the house ReplyStandard rules PLUS alex (insensitive / inconsiderate
; language), vendored under styles/alex from errata-ai/alex v0.2.3 (MIT — see
; styles/alex/LICENSE; vendored 2026-08-29 via `vale sync`, unmodified).
; Selected by hooks.valeStyle: "alex".
StylesPath = styles
MinAlertLevel = suggestion

[*.md]
BasedOnStyles = ReplyStandard, alex

ReplyStandard.Dashes = NO
