; The redhat profile: the house ReplyStandard rules PLUS the Red Hat supplementary style
; guide, vendored under styles/RedHat from redhat-documentation/vale-at-red-hat v677
; (MIT — see styles/RedHat/LICENSE; vendored 2026-08-29 via `vale sync`, unmodified).
; Selected by hooks.valeStyle: "redhat".
StylesPath = styles
MinAlertLevel = suggestion

[*.md]
BasedOnStyles = ReplyStandard, RedHat

ReplyStandard.Dashes = NO
