; RAW upstream Google developer-documentation style — no house rules, no tuning.
; Vendored under styles/Google from errata-ai/Google v0.7.1 (MIT — see
; styles/Google/LICENSE; vendored 2026-08-29 via `vale sync`, unmodified).
; Selected by hooks.valeStyle: "google". The tuned default is the sibling
; .vale-workauditrefine.ini (the WorkAuditRefine fork).
StylesPath = styles
MinAlertLevel = suggestion

[*.md]
BasedOnStyles = Google
