; The readability profile: the house ReplyStandard rules PLUS Readability (Flesch-Kincaid,
; Gunning fog, and five more metrics), vendored under styles/Readability from
; errata-ai/Readability v0.1.1 (MIT — see styles/Readability/LICENSE; vendored 2026-08-29
; via `vale sync`, unmodified). Selected by hooks.valeStyle: "readability".
StylesPath = styles
MinAlertLevel = suggestion

[*.md]
BasedOnStyles = ReplyStandard, Readability

ReplyStandard.Dashes = NO
