; The proselint profile: the house WorkAuditRefine rules PLUS the proselint port (jargon,
; redundancy, corporate speak), vendored under styles/proselint from
; errata-ai/proselint v0.3.4 (BSD-3 — see styles/proselint/LICENSE; vendored 2026-08-29
; via `vale sync`, unmodified). Selected by hooks.valeStyle: "proselint".
StylesPath = styles
MinAlertLevel = suggestion

[*.md]
BasedOnStyles = WorkAuditRefine, proselint

WorkAuditRefine.Dashes = NO
